// <auto-generated />
namespace DeanOfficeApp.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class moremodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(moremodels));
        
        string IMigrationMetadata.Id
        {
            get { return "201710092145008_more models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
