USE [master]
GO

/****** Object:  Database [DB_A2C8B2_deanOffice]    Script Date: 07.12.2017 16:45:52 ******/
CREATE DATABASE [DB_A2C8B2_deanOffice]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_A2C8B2_deanOffice_Data', FILENAME = N'H:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DB_A2C8B2_deanOffice_data.mdf' , SIZE = 8192KB , MAXSIZE = 512000KB , FILEGROWTH = 10%)
 LOG ON 
( NAME = N'DB_A2C8B2_deanOffice_Log', FILENAME = N'H:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DB_A2C8B2_deanOffice_log.ldf' , SIZE = 3072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DB_A2C8B2_deanOffice] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_A2C8B2_deanOffice].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DB_A2C8B2_deanOffice] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DB_A2C8B2_deanOffice] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DB_A2C8B2_deanOffice] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DB_A2C8B2_deanOffice] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DB_A2C8B2_deanOffice] SET ARITHABORT OFF 
GO

ALTER DATABASE [DB_A2C8B2_deanOffice] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DB_A2C8B2_deanOffice] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DB_A2C8B2_deanOffice] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DB_A2C8B2_deanOffice] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DB_A2C8B2_deanOffice] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DB_A2C8B2_deanOffice] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DB_A2C8B2_deanOffice] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DB_A2C8B2_deanOffice] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DB_A2C8B2_deanOffice] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DB_A2C8B2_deanOffice] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DB_A2C8B2_deanOffice] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DB_A2C8B2_deanOffice] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DB_A2C8B2_deanOffice] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DB_A2C8B2_deanOffice] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DB_A2C8B2_deanOffice] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DB_A2C8B2_deanOffice] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DB_A2C8B2_deanOffice] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DB_A2C8B2_deanOffice] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DB_A2C8B2_deanOffice] SET  MULTI_USER 
GO

ALTER DATABASE [DB_A2C8B2_deanOffice] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DB_A2C8B2_deanOffice] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DB_A2C8B2_deanOffice] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DB_A2C8B2_deanOffice] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DB_A2C8B2_deanOffice] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DB_A2C8B2_deanOffice] SET QUERY_STORE = OFF
GO

USE [DB_A2C8B2_deanOffice]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [DB_A2C8B2_deanOffice] SET  READ_WRITE 
GO

